// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package todo

import (
	"github.com/rudolfoborges/google-wire-sample/internal/dataproviders"
	"github.com/rudolfoborges/google-wire-sample/internal/domain/todo/controllers"
	"github.com/rudolfoborges/google-wire-sample/internal/domain/todo/usecases"
)

// Injectors from wire.go:

func NewTodoController() *controllers.TodoController {
	todoRepository := dataproviders.NewTodoRepository()
	createTodo := usecases.NewCreateTodoUseCase(todoRepository)
	fetchTodos := usecases.NewFetchTodosUseCase(todoRepository)
	completeTodo := usecases.NewCompleteTodoUseCase(todoRepository)
	todoController := controllers.NewTodoController(createTodo, fetchTodos, completeTodo)
	return todoController
}
